### PR TITLE
Artcile update

### PR DESCRIPTION
**Pull request by kemanedonfack**

### CODE REVIEW

**Review by dassiorleando — CHANGES_REQUESTED** [review]
image

**Comment by dassiorleando** [comment]
@kemanedonfack, could you please confirm that you tested it all and that the **WordPress** uploads feature used the same file system?

**Comment by dassiorleando** [comment]
Reminder: for the next PR it'll be good to work from a branch that is derived from your master one so that you'll fetch updates from the main repository easily and we won't have any conflicts at all.

**Comment by kemanedonfack** [comment]
> @kemanedonfack, could you please confirm that you tested it all and that the **WordPress** uploads feature used the same file system?

yes, everything works as planned

**Comment by kemanedonfack** [comment]
> Reminder: for the next PR it'll be good to work from a branch that is derived from your master one so that you'll fetch updates from the main repository easily and we won't have any conflicts at all.

Okay understood

**Comment by kemanedonfack** [comment]
> image

I don't understand

**Review by dassiorleando — APPROVED** [review]

**Pull request merged**
